# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
#       Stop all: docker-compose down
#
version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_URL=postgres://ykxtnlrdjtnsil:a9e617d7d190942b3cdd32a5ff841e9f870c4915a89fa8f576ab1571d2a98b57@ec2-52-5-167-89.compute-1.amazonaws.com:5432/d88uceache1fg
  DATABASE_HOST=localhost
  DATABASE_PORT=5432
  DATABASE_USERNAME=kazzer
  DATABASE_NAME=myDB
  
services:
  app:
    image: gib-backend:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0"]
